### ISSUE TITLE
Get shadow length - possible?

### ISSUE THREAD

**Issue by ibragimof** [gregseth/suncalc-php#19]

**Comment by hnccox-yard** [comment]
Wouldn't the length of any shadow be depending on the height of the object?
What are you even trying to do?

**Comment by ibragimof** [comment]
The length of the shadow depends on where the sun is and at what angle its rays hit the object.

If the ratio coefficient of the real length of the object to its real shadow length can be obtained for a one-inch object, it is applicable to all objects regardless of their scale. You can obtain results like "shadow length 50%" (half of the object's real height). I've already implemented this function, by the way.

If something is unclear to you specifically, it doesn't mean that others are fools.

**Comment by hnccox-yard** [comment]
"The length of the shadow depends on where the sun is and at what angle its rays hit the object."

Correct, but the length from here on would be depending on the height of the object itself.
You can use pythagoras theorem for this.
You can get the ratio by dividing the length of the shadow with the height of the object.

EDIT: If the object is really high, you need to consider the curvature of the earth

PS: Noone said you are a fool, your question statement is unclear as you didn't provide all the parameters you consider.

**Comment by ibragimof** [comment]
Are you laughing or genuinely not getting what I'm talking about?! With just 10 lines of code, you can achieve a result where, regardless of the object's height, you get an accurate proportion of its shadow.

For the specific tasks in my work, I don't need to know the height of the object. Moreover, it's not possible considering the various gradations of working objects.

Where does the Pythagorean triangle come into play when I don't have tools to measure height or the angle of inclination?

**Comment by ibragimof** [comment]
![2023-11-27 19-5-1](https://github.com/gregseth/suncalc-php/assets/47029060/f6dd427b-5f74-4ef5-afc7-e50b8af9173a)

**Comment by ibragimof** [comment]
https://en.wikipedia.org/w/index.php?title=Salah_times&section=7&oldid=1186511348&action=edit

**Comment by ibragimof** [comment]
https://www.moonsighting.com/how-we.html

**Comment by hnccox-yard** [comment]
> ![2023-11-27 19-5-1](https://private-user-images.githubusercontent.com/47029060/286917683-f6dd427b-5f74-4ef5-afc7-e50b8af9173a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDA3NjMsIm5iZiI6MTcwMTcwMDQ2MywicGF0aCI6Ii80NzAyOTA2MC8yODY5MTc2ODMtZjZkZDQyN2ItNWY3NC00ZWY1LWFmYzctZTUwYjhhZjkxNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjE4NWIwM2RmYTI0MDU1NGVhOTVmNmNiMWVmYjIwNTkxZGE3NmU0MWE5NmU1YjQwNzJhYmY5MzcxYmJkYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DC27_0gAOgfdDW4H9sCKIxJyx8AZAWMuQAHzZ86vszw)

Now you are just being rude and retarded.
You are literally posting a picture where you give the height of the object to be 67 meters!
You need to know the height of the object and the angle of the sun to be able to calculate the length of it's shadow.

To find the lengths of sides A and B in a right-angled triangle given the angle at corner C, you'll need additional information such as the length of side AC (the hypotenuse) or another angle. If you have the length of the hypotenuse and the angle at C, you can use trigonometric functions.

If you set AC to be 1, you can get the ratio to AB

Also, you said LENGTH in your question, not proportion or ratio

**Comment by hnccox-yard** [comment]
Dumb ass russian muslim

**Comment by hnccox-yard** [comment]
They don't come much thicker than russian muslims

**Comment by ibragimof** [comment]
> Now you are just being rude and retarded. You are literally posting a picture where you give the height of the object to be 67 meters! You need to know the height of the object and the angle of the sun to be able to calculate the length of it's shadow.

There's nothing inherently bad about an object being 67 meters long. The relationship between the height of an object and the length of its shadow varies throughout the day, and this proportion is independent of the object's length. If there's any complexity in my understanding, feel free to provide more details or clarify. I'm here to help with any questions you have.

**Comment by ibragimof** [comment]
Ну и что, что длина объекта будет 67 метров? В разные часы суток отношение его высоты к длине тени постоянно меняется. Пропорции тут не зависят от того, насколько велика эта ваша штуковина. Может, это для тебя сложно, но не вини в этом мусульман.
