### ISSUE TITLE
still the same problem

### ISSUE THREAD

**Issue by pketola** [gregseth/suncalc-php#2]
I tested on PHP 5.6.x and get error message on same function:

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (@NAN) at position 0 (@): Unexpected character' in C:\xampp\htdocs\moon-test\stest.php:43 Stack trace: #0 C:\xampp\htdocs\moon-test\stest.php(43): DateTime->__construct('@NAN') #1 C:\xampp\htdocs\moon-test\stest.php(224): fromJulian(-1.#IND) #2 C:\xampp\htdocs\moon-test\stest.php(331): SunCalc->getSunTimes() #3 {main} thrown in C:\xampp\htdocs\moon-test\stest.php on line 43

function fromJulian($j)  {
    $dt = new DateTime("@".round(($j + 0.5 - J1970) * daySec));
    $dt->setTimezone((new DateTime())->getTimezone());
    return $dt;
}

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21

**Comment by gregseth** [comment]
Yes sorry, I googled the issue a bit too quickly. Latest commit should fix the problem.
